networks:
  mailtest_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  postfix:
    image: mailtest-postfix
    build:
      context: ./postfix
    container_name: mailtest-postfix
    networks:
      mailtest_net:
        ipv4_address: 172.28.0.10
    volumes:
      - ./pki/profiles:/etc/mailtest/pki:ro
      - ./postfix/templates:/etc/mailtest/templates:ro
      - ./active:/etc/mailtest/active

  dovecot:
    build:
      context: ./dovecot
    container_name: mailtest-dovecot
    networks:
      mailtest_net:
        ipv4_address: 172.28.0.11
    volumes:
      - ./pki/profiles:/etc/mailtest/pki:ro
      - ./dovecot/templates:/etc/mailtest/templates:ro
      - ./active:/etc/mailtest/active

  client:
    build:
      context: ./client
    container_name: mailtest-client
    networks:
      mailtest_net:
        ipv4_address: 172.28.0.20
    volumes:
      - ./client/scripts:/scripts:ro
      - ./client/openssl:/etc/mailtest/openssl:ro
      - ./pki/profiles:/etc/mailtest/pki:ro

  mitm:
    image: python:3.12-slim
    container_name: mailtest-mitm
    networks:
      mailtest_net:
        ipv4_address: 172.28.0.30
    volumes:
      - ./mitm:/mitm:ro
    command: ["python3", "-u", "/mitm/main.py"]

  legacy:
    image: mailtest-legacy:latest
    build:
      context: ./legacy
    container_name: mailtest-legacy
    networks:
      mailtest_net:
        ipv4_address: 172.28.0.40
    volumes:
      - ./legacy:/legacy
      - ./pki/profiles:/etc/mailtest/pki:ro
      - ./active:/etc/mailtest/active


