import type { ComponentType, ReactNode } from 'react'
import './ResearchReport.css'

type Props = { Brand: ComponentType<{ compact?: boolean }> }

function Section({ id, index, title, children }: { id: string; index: string; title: string; children: ReactNode }) {
  return <section id={id} className="paper-section"><div className="paper-section-label"><span>{index}</span><i /></div><div className="paper-section-content"><h2>{title}</h2>{children}</div></section>
}

function Figure({ number, title, caption, children }: { number: string; title: string; caption: string; children: ReactNode }) {
  return <figure className="research-figure"><div className="research-figure-heading"><span>FIGURE {number}</span><b>{title}</b></div><div className="research-figure-body">{children}</div><figcaption>{caption}</figcaption></figure>
}

function ArchitectureFigure() {
  return <svg className="research-svg architecture-svg architecture-svg-vertical" viewBox="0 0 780 900" role="img" aria-labelledby="architecture-title architecture-desc">
    <title id="architecture-title">SecureMailScope forensic architecture</title>
    <desc id="architecture-desc">PCAP files flow through TCP stream reconstruction, email protocol and TLS parsing, then branch into independent deterministic rule evaluation and advisory machine learning. Their separate outputs join the evidence report without ML overriding policy findings.</desc>
    <defs><marker id="arch-arrow" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto"><path d="M0 0L9 4.5L0 9" fill="none" stroke="#e82e3e" strokeWidth="1.5" /></marker></defs>
    <text className="svg-kicker" x="390" y="26" textAnchor="middle">PASSIVE PCAP EVIDENCE → STRUCTURED FORENSIC RESULT</text>
    <g className="svg-box"><rect x="250" y="55" width="280" height="92"/><text className="svg-index" x="390" y="79" textAnchor="middle">01 · INPUT</text><text className="svg-title" x="390" y="104" textAnchor="middle">PCAP / PCAPNG</text><text className="svg-copy" x="390" y="127" textAnchor="middle">Captured packets · timestamps · direction</text></g>
    <path className="svg-arrow" d="M390 147V174" markerEnd="url(#arch-arrow)"/>
    <g className="svg-box"><rect x="190" y="183" width="400" height="156"/><text className="svg-index" x="390" y="208" textAnchor="middle">02 · PARSER AND SESSION RECONSTRUCTION</text><text className="svg-title" x="390" y="237" textAnchor="middle">TCP flows → SMTP · IMAP · POP3</text><text className="svg-copy" x="390" y="262" textAnchor="middle">Sequence, direction, and application protocol</text><text className="svg-copy" x="390" y="282" textAnchor="middle">STARTTLS / implicit TLS state transitions</text><text className="svg-copy" x="390" y="310" textAnchor="middle">Unknown and unavailable values stay explicit</text></g>
    <path className="svg-arrow" d="M390 339V366" markerEnd="url(#arch-arrow)"/>
    <g className="svg-box"><rect x="190" y="375" width="400" height="141"/><text className="svg-index" x="390" y="400" textAnchor="middle">03 · CANONICAL OBSERVATIONS</text><text className="svg-title" x="390" y="430" textAnchor="middle">TLS handshake and X.509 evidence</text><text className="svg-copy" x="390" y="455" textAnchor="middle">Version · cipher · key exchange · forward secrecy</text><text className="svg-copy" x="390" y="477" textAnchor="middle">Certificate path · identity · validity · key · extensions</text><text className="svg-copy" x="390" y="500" textAnchor="middle">Feature coverage and provenance accompany evidence</text></g>
    <path className="svg-branch" d="M390 516V546H205V570" markerEnd="url(#arch-arrow)"/><path className="svg-branch" d="M390 546H575V570" markerEnd="url(#arch-arrow)"/>
    <g className="svg-box svg-rule"><rect x="45" y="579" width="320" height="112"/><text className="svg-index" x="205" y="606" textAnchor="middle">04A · AUTHORITATIVE</text><text className="svg-title" x="205" y="635" textAnchor="middle">Deterministic Rule Engine</text><text className="svg-copy" x="205" y="660" textAnchor="middle">Standards checks · findings · evidence</text><text className="svg-copy" x="205" y="678" textAnchor="middle">Posture heuristic remains separate</text></g>
    <g className="svg-box svg-ml"><rect x="415" y="579" width="320" height="112"/><text className="svg-index" x="575" y="606" textAnchor="middle">04B · ADVISORY</text><text className="svg-title" x="575" y="635" textAnchor="middle">Machine-learning layer</text><text className="svg-copy" x="575" y="660" textAnchor="middle">Risk rubric · cohort-relative novelty</text><text className="svg-copy" x="575" y="678" textAnchor="middle">Model and provenance stay explicit</text></g>
    <path className="svg-branch" d="M205 691V728H390"/><path className="svg-branch" d="M575 691V728H390"/><path className="svg-arrow" d="M390 728V749" markerEnd="url(#arch-arrow)"/>
    <g className="svg-output"><rect x="160" y="758" width="460" height="91"/><text className="svg-index" x="390" y="784" textAnchor="middle">05 · STORED CASE RESULT</text><text className="svg-title" x="390" y="811" textAnchor="middle">Evidence-led forensic report</text><text className="svg-copy" x="390" y="833" textAnchor="middle">Separate findings and ML · JSON / HTML / print PDF</text></g>
    <text className="svg-foot" x="390" y="881" textAnchor="middle">ML DOES NOT SUPPRESS OR OVERRIDE A RULE ENGINE FINDING</text>
  </svg>
}

function ProtocolFlowFigure() {
  const nodes = [
    ['A', 'Capture input', 'PCAP packets grouped by TCP stream'],
    ['B', 'Identify mail protocol', 'Payload evidence; ports are supporting context'],
    ['C', 'Track cleartext negotiation', 'SMTP EHLO / IMAP capability / POP3 STLS'],
    ['D', 'Resolve encryption transition', 'Advertised → requested → accepted → TLS'],
    ['E', 'Reconstruct TLS evidence', 'Handshake fields; certificate only if visible'],
    ['F', 'Emit explicit state', 'Observed · not observed · not applicable · unknown'],
  ]
  return <div className="protocol-flow" role="list" aria-label="Protocol parsing sequence">{nodes.map(([id, title, copy]) => <div className="protocol-flow-step" role="listitem" key={id}><span>{id}</span><b>{title}</b><small>{copy}</small></div>)}</div>
}

function ProvenanceFigure() {
  return <svg className="research-svg provenance-svg" viewBox="0 0 1020 470" role="img" aria-labelledby="provenance-title provenance-desc">
    <title id="provenance-title">Data source provenance and model usage</title><desc id="provenance-desc">Five separate dataset streams: Censys-derived targets to active ZGrab SMTP; generated testbed PCAPs for parser validation; real HTTPS captures for TLS novelty only; SMTP-related certificate corpus for certificate novelty; and NVD KEV EPSS and standards knowledge for enrichment, not classifier training.</desc>
    <defs><marker id="prov-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="none" stroke="#9a9390" strokeWidth="1.2"/></marker></defs>
    <text className="svg-kicker" x="22" y="22">SOURCE COLLECTION</text><text className="svg-kicker" x="390" y="22">TRANSFORMATION / CORPUS</text><text className="svg-kicker" x="761" y="22">SUPPORTED USE</text>
    {[
      { y: 54, a: 'Censys-derived IP targets', b: '16 countries · 100 targets each', c: 'ZGrab2 active SMTP scan', d: '1,600 SMTP observations', e: 'SMTP evidence classifier', f: '+ SMTP reference cohort' },
      { y: 132, a: 'Controlled testbed scenarios', b: 'SMTP · IMAP · POP3 · TLS states', c: '110 generated PCAP captures', d: '116 parsed streams · synthetic', e: 'Parser · rules · runtime', f: 'integration checks' },
      { y: 210, a: 'Public TLS PCAP collection', b: 'mix.zip · HTTPS cohort', c: '41,205 real TLS captures', d: 'TLS 1.3 · 41 site groups', e: 'HTTPS novelty only', f: 'not an email model' },
      { y: 288, a: 'MTA-STS scan context', b: 'certificate records', c: '21,490 parsed · 9,459 unique', d: 'not SMTP handshake sessions', e: 'Certificate novelty', f: 'reference cohort' },
      { y: 366, a: 'NVD · CISA KEV · EPSS', b: 'CWE · NIST · OWASP', c: 'threat intel + knowledge', d: 'not network observations', e: 'Evidence-linked', f: 'enrichment only' },
    ].map((row) => <g key={row.y}>
      <g className="svg-box"><rect x="20" y={row.y} width="255" height="60"/><text className="svg-title" x="35" y={row.y + 25}>{row.a}</text><text className="svg-copy" x="35" y={row.y + 46}>{row.b}</text></g>
      <path className="svg-arrow-muted" d={`M275 ${row.y + 30}H320`} markerEnd="url(#prov-arrow)"/>
      <g className="svg-box"><rect x="330" y={row.y} width="300" height="60"/><text className="svg-title" x="347" y={row.y + 25}>{row.c}</text><text className="svg-copy" x="347" y={row.y + 46}>{row.d}</text></g>
      <path className="svg-arrow-muted" d={`M630 ${row.y + 30}H675`} markerEnd="url(#prov-arrow)"/>
      <g className="svg-box"><rect x="685" y={row.y} width="315" height="60"/><text className="svg-title provenance-output" x="702" y={row.y + 25}>{row.e}</text><text className="svg-copy" x="702" y={row.y + 45}>{row.f}</text></g>
    </g>)}
  </svg>
}

function BarChart({ title, rows, max, note }: { title: string; rows: Array<{ label: string; value: number; color?: string }>; max: number; note?: string }) {
  return <div className="bar-chart"><h4>{title}</h4><div className="bar-chart-rows">{rows.map((row) => <div className="bar-chart-row" key={row.label}><span>{row.label}</span><div className="bar-track"><i style={{ width: `${Math.max(row.value / max * 100, row.value ? 1 : 0)}%`, background: row.color || '#e82e3e' }} /></div><b>{row.value.toLocaleString()}</b></div>)}</div>{note && <p>{note}</p>}</div>
}

function Matrix({ title, labels, rows }: { title: string; labels: string[]; rows: number[][] }) {
  return <div className="matrix-card"><h4>{title}</h4><div className="matrix-scroll"><table className="confusion-matrix"><caption>Rows: actual class · columns: predicted class</caption><thead><tr><th>Actual ↓ / Predicted →</th>{labels.map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={labels[i]}><th>{labels[i]}</th>{row.map((v, j) => <td key={`${i}-${j}`} className={i === j ? 'matrix-diagonal' : ''}>{v}</td>)}</tr>)}</tbody></table></div></div>
}

function ModelCard({ title, badge, children }: { title: string; badge: string; children: ReactNode }) {
  return <article className="model-card"><div className="model-card-head"><span>{badge}</span><h3>{title}</h3></div>{children}</article>
}

export function ResearchReport({ Brand }: Props) {
  return <div className="paper-site research-site">
    <header className="paper-header"><Brand compact /><div className="paper-actions"><a href="https://github.com/Ben160804/SES-v1" className="paper-link" target="_blank" rel="noreferrer">GitHub repository <span>↗</span></a><a href="/workspace" className="paper-link">Analysis workspace <span>↗</span></a><button className="icon-button print-button" onClick={() => window.print()} aria-label="Print or save this report as PDF">PRINT / SAVE PDF</button></div></header>
    <div className="paper-layout research-layout">
      <aside className="paper-index"><span className="index-heading">PAPER CONTENTS</span><a href="#abstract">Abstract</a><a href="#problem">Problem & contribution</a><a href="#architecture">Architecture</a><a href="#parser">Parser methodology</a><a href="#rules">Rule engine</a><a href="#data">Data & provenance</a><a href="#testbed">Testbed design</a><a href="#ml">ML methods</a><a href="#evaluation">Evaluation</a><a href="#runtime">Runtime & outputs</a><a href="#limitations">Limitations</a><a href="#reproducibility">Reproducibility</a><a href="#references">References</a></aside>
      <article className="paper research-paper">
        <div className="paper-kicker"><span>SIH PROBLEM STATEMENT 26159</span><span>NTRO · TECHNICAL RESEARCH REPORT</span></div>
        <h1>SecureMailScope</h1>
        <p className="paper-deck">Passive forensic reconstruction and cryptographic posture assessment for SMTP, IMAP, and POP3</p>
        <div className="research-authors"><span>Project technical report</span><span>Implementation and validation record</span></div>
        <div className="paper-rule" />

        <Section id="abstract" index="00" title="Abstract">
          <p className="paper-lead">Email transport security depends on more than whether a packet capture contains TLS. Investigators need to determine which mail protocol was used, whether encryption was negotiated or upgraded, what cryptographic parameters were selected, what certificate evidence was visible, and which conclusions are supported by the capture. SecureMailScope is an offline forensic framework that reconstructs SMTP, IMAP, and POP3 TCP conversations from PCAP/PCAPNG, extracts TLS and X.509 evidence, evaluates deterministic policy profiles, and attaches separate advisory machine-learning (ML) estimates.</p>
          <p>The processing design has four substantive stages: (i) stream reconstruction and protocol-aware state interpretation; (ii) canonical TLS, STARTTLS, handshake, and certificate feature extraction; (iii) standards-oriented rule evaluation and heuristic posture summarization; and (iv) cohort-bounded ML classification and novelty analysis. The rules and ML consume the same observed session but remain separate. ML cannot suppress a deterministic policy failure. The system preserves missing and unobservable fields as such, which is essential in passive analysis: for example, TLS 1.3 encrypts the certificate handshake after ServerHello, so a capture without session secrets may not expose the certificate.</p>
          <p>Evaluation uses heterogeneous evidence with explicit provenance rather than merging unlike data. The real-world SMTP cohort consists of 1,600 active ZGrab observations from Censys-derived targets, including 530 successful TLS handshakes. It is not a passive PCAP corpus. A generated 10,000-row email feature cohort trains the current IMAP/POP3 endpoint-posture classifier; the rows are simulated, not captured traffic. Separately, 110 controlled synthetic PCAPs exercise parser and runtime behavior, while 41,205 real HTTPS TLS PCAPs support only a non-email novelty cohort. A certificate-only corpus supports certificate novelty. Held-out metrics describe agreement with project-defined rubrics or behavior within the stated data-generating cohort; they do not establish independent risk ground truth, attack detection, or production accuracy.</p>
          <div className="abstract-facts"><div><b>1,600</b><span>active SMTP observations</span></div><div><b>110</b><span>controlled email PCAPs</span></div><div><b>3</b><span>mail protocols represented</span></div><div><b>0</b><span>independent human-reviewed risk labels</span></div></div>
          <div className="keyword-line"><b>KEYWORDS</b> passive network forensics · SMTP · IMAP · POP3 · STARTTLS · TLS · X.509 · policy evaluation · anomaly detection · data provenance</div>
        </Section>

        <Section id="problem" index="01" title="Problem formulation and contribution">
          <p>The SIH problem statement asks for passive analysis of encrypted email communications, protocol and encryption-transition identification, reconstruction of TLS negotiation, certificate analysis, detection of weak configurations, AI-assisted risk classification and anomaly detection, posture scoring, threat prioritization, and actionable recommendations. SecureMailScope treats a packet capture as incomplete forensic evidence rather than as a perfect endpoint inventory. The core question is therefore: <em>what security-relevant facts can be established from the observed traffic, which checks can be applied to those facts, and which additional model outputs can be reported without overstating their meaning?</em></p>
          <p>This framing matters because an observed TLS session is only one sample from an endpoint's configuration. A session selecting a modern cipher does not prove that the endpoint rejects weak alternatives; a missing certificate does not prove the endpoint has none; a failed handshake is not a safe configuration. The system consequently distinguishes <b>observed facts</b>, <b>deterministic policy outcomes</b>, <b>cohort-relative model estimates</b>, and <b>not-evaluable states</b>.</p>
          <div className="contribution-grid"><div><span>01</span><b>Forensic reconstruction</b><p>Correlates protocol state, encryption transitions, TLS negotiation, and certificate telemetry at stream scope.</p></div><div><span>02</span><b>Policy and ML separation</b><p>Rule findings remain authoritative; learned estimates are additional signals with their own target and provenance.</p></div><div><span>03</span><b>Heterogeneous evidence</b><p>Active scans, synthetic PCAPs, HTTPS captures, certificate records, and threat intelligence keep distinct roles.</p></div><div><span>04</span><b>Transparent uncertainty</b><p>Coverage, applicability, cohort, missing evidence, and limitations travel with results.</p></div></div>
        </Section>

        <Section id="architecture" index="02" title="System architecture">
          <p>Figure 1 shows the end-to-end path. Parsing produces a canonical per-stream record before any assessment is made. The Rule Engine and ML runtime then operate as parallel consumers of that record. This prevents model outputs from being mistaken for standards checks and lets an analyst compare the same evidence with the policy verdict and a separately defined statistical estimate.</p>
          <Figure number="1" title="End-to-end passive analysis and assessment architecture" caption="The Rule Engine and ML layer receive canonical observations independently. Stored assessment preserves those result types rather than collapsing them into a single learned score. The product's deterministic posture summary is explicitly a heuristic and remains separate from ML."><ArchitectureFigure /></Figure>
          <div className="paper-callout"><b>Separation invariant</b><span>A rule finding is a deterministic result under a named policy and its observed inputs. A classifier predicts its documented target; a novelty detector compares an observation with a named cohort. Their scores are not interchangeable, and ML never overrides the Rule Engine.</span></div>
          <p>Analysis results are persisted per capture and stream, with evidence identifiers, observations, policy results, posture summaries, and ML outputs. The frontend can therefore present both capture-level aggregation and stream-level detail. JSON and HTML report exports preserve the distinction; the print interface can be saved as PDF by the browser.</p>
        </Section>

        <Section id="parser" index="03" title="Parser and feature-engineering methodology">
          <p>The parser orchestrator (<code>analysis/parser.py</code>) coordinates protocol DPI, STARTTLS state analysis, TLS handshake reconstruction, certificate extraction, and trust-store evaluation. It forms a union of stream identifiers returned by these extractors and emits a unified record per stream. This correlation design allows a stream to retain protocol observations even when one of its TLS or certificate extractors has no result.</p>
          <h3 className="subhead">3.1 Stream and protocol reconstruction</h3>
          <p>Input PCAP/PCAPNG packets are processed offline. TCP conversations are identified by stream and direction; application payload is examined for SMTP, IMAP, and POP3 indicators. Port numbers are contextual evidence, not sufficient proof on their own. Protocol inference and STARTTLS analysis are delegated to the protocol/state module. It tracks the application-level sequence required to interpret encryption upgrades: server capability or extension, client request, server acceptance or rejection, observed TLS activation, and plaintext-authentication observations. Implicit TLS is represented separately from an in-band upgrade.</p>
          <p>This state model avoids reducing STARTTLS to a Boolean. “Advertised but not requested,” “request rejected,” “accepted but no visible handshake,” and “TLS active” represent different forensic situations and have different evidentiary implications. The implementation records a status and explanation for these transitions so downstream rules can distinguish a confirmed weakness from incomplete capture evidence.</p>
          <Figure number="2" title="Mail-protocol and encryption-transition interpretation" caption="The protocol state machine uses ordered application and handshake evidence. The final state is not inferred from absence alone: incomplete or encrypted visibility is retained as uncertainty."><ProtocolFlowFigure /></Figure>
          <h3 className="subhead">3.2 TLS and handshake facts</h3>
          <p>TLS extraction records negotiated protocol version, cipher suite, key-exchange/group evidence, handshake lifecycle information, downgrade signals, extensions, and forward-secrecy-relevant state where the capture exposes it. TLS 1.2 and TLS 1.3 differ in what a passive observer can see. In TLS 1.3, the server's certificate message is encrypted after ServerHello; without session traffic secrets, a PCAP can reveal the negotiated TLS parameters while leaving the certificate unavailable. The application therefore reports observability, rather than filling such fields with zero or assuming a negative.</p>
          <h3 className="subhead">3.3 Certificate extraction and validation</h3>
          <p>When certificates are transmitted in clear handshake messages and captured, the certificate subsystem parses the leaf and available intermediates. Extracted attributes include subject and issuer context, validity interval, SANs, public-key algorithm and size, signature algorithm, key usage, extended key usage, basic constraints, and selected extensions. Validation checks certificate signatures and path construction against the configured trust store; hostname matching is evaluated only where the capture supplies a defensible reference name. These are distinct questions: a path anchored in the analyzer's configured trust bundle does not prove that a particular client accepted the certificate, and offline captures cannot generally perform live revocation checks.</p>
          <p>Canonical features expose categorical values, numeric measurements, and explicit observation state. Predictive models exclude identifiers such as IP addresses, country, timestamps, and record IDs. Categorical fields are encoded in the model pipeline. Numeric missingness uses indicators or semantic observation flags; absent TLS/certificate values are not globally converted to zero. Runtime coverage and abstention are emitted alongside predictions.</p>
          <div className="feature-pills"><span>Protocol state</span><span>STARTTLS transition</span><span>TLS version</span><span>Cipher / AEAD / CBC</span><span>Key exchange / PFS</span><span>Handshake lifecycle</span><span>Certificate presence</span><span>Key / signature</span><span>Validity / SAN</span><span>Extensions / usage</span><span>Observation flags</span><span>Provenance (metadata only)</span></div>
        </Section>

        <Section id="rules" index="04" title="Deterministic Rule Engine and posture summary">
          <p>The Rule Engine in <code>analysis/rule_engine/</code> builds a typed rule input from parser output and dispatches it to separate evaluators. Current policy packs include NIST SP 800-52 Rev. 2, NIST SP 800-131A, and Mozilla Modern and Intermediate profiles. A policy result is evaluated against concrete facts such as negotiated TLS version, cipher suite, key-exchange group, certificate algorithm and size, signature hash, validity, name, and extension usage. A separate observations evaluator records forensic conditions such as cleartext operation, STARTTLS behavior, plaintext authentication, and TLS handshake evidence.</p>
          <p>Every check can be passed, failed, not applicable, or not observable. This is crucial for a forensic tool: a certificate-lifespan requirement cannot be evaluated if no certificate was visible, and an IMAP-specific negotiation rule may not apply to a different protocol. Findings carry the relevant rule identifier, result, explanation, and evidence snapshot. A detected weakness may also carry evidence-linked remediation guidance; generic CVE identifiers are not inferred from a weak cipher or protocol label.</p>
          <p>The separate “security posture” number is computed by <code>analysis/posture.py</code> from deterministic findings and weights. It is a project heuristic on a 0–100 scale, not a calibrated probability, learned classifier score, or external certification. It should be read with the specific failed checks and coverage counts. A high score cannot negate a particular failed policy check.</p>
          <div className="two-column-note"><div><b>Rule Engine answers</b><p>“Did the observed session violate this named deterministic policy check?”</p></div><div><b>ML answers</b><p>“What rubric class or cohort-relative novelty signal follows from the model's inputs?”</p></div></div>
        </Section>

        <Section id="data" index="05" title="Data acquisition, corpus composition, and provenance">
          <p>The project does not have a single universal training dataset. Each corpus has a bounded role. Figure 3 traces those paths. In particular, the real-world SMTP classifier data came from active application-layer measurements against Censys-derived IP targets using ZGrab2, not from passively recorded corporate mail. The generated email data is a separate feature simulation; the testbed PCAPs are synthetic wire captures; and the large HTTPS corpus is not email traffic.</p>
          <p><b>SMTP acquisition procedure.</b> Censys-derived target lists were prepared for 16 countries (United States, United Kingdom, Germany, France, Russia, Netherlands, India, Canada, Japan, Australia, South Korea, Singapore, Italy, Spain, Brazil, and Mexico), with approximately 100 unique targets per country. The ZGrab2 SMTP module then made application-layer SMTP connections against submission port 587, using a bounded connection rate and timeout configuration, and saved JSON handshake observations. The project feature extractor converted those records to the 1,600-row, approximately 88-column <code>zgrab_features.csv</code>. The original feature inventory includes SMTP state, TLS negotiation and extension flags, cipher/KEX properties, certificate features, and several deterministic risk fields. The supervised evidence-rubric model uses a narrower 15-feature schema: identifiers and direct rule/risk flags are excluded so that the target is not trivially copied from the fields being predicted. TLS/certificate values remain semantically missing when not observed.</p>
          <p>The same target population was explored for IMAP and POP3 on ports 143 and 110 in a 100-target Mexico sample. The scans yielded 74 successful application responses per protocol and exposed banners/capabilities, including STARTTLS advertisement. They did not provide a comparably sized, labeled corpus of negotiated IMAP/POP3 TLS sessions. A port 993 IMAPS probe yielded one banner-only response without negotiated TLS/certificate details. Consequently, these records establish that the project checked real IMAP/POP3 services; they do not train or validate the current IMAP/POP3 cryptographic classifier.</p>
          <Figure number="3" title="Data lineage and task-specific cohort boundaries" caption="Each data path is retained as a separate provenance class. The number at one stage does not imply that every source row is usable for every model. Project-relative paths are given in Table 1; source links appear in References."><ProvenanceFigure /></Figure>
          <div className="data-table-wrap"><table className="data-table research-table"><caption>Table 1. Dataset inventory and permitted interpretation</caption><thead><tr><th>Source / local artifact</th><th>Size and type</th><th>Use in this project</th><th>Boundary / provenance</th></tr></thead><tbody>
            <tr><td>Censys-derived targets → ZGrab2 SMTP<br/><code>datasets/ml/zgrab/zgrab_features.csv</code></td><td>1,600 targets/observations across 16 countries; 1,524 SMTP successes, 76 failures; 531 STARTTLS, 530 handshakes and certificates.</td><td>Real SMTP evidence-rubric classifier, separate handshake proxy experiments, and SMTP negotiation cohort.</td><td>Active Internet scanning of real IPs, not passive PCAP. Of 1,600 records, only completed/evaluable subsets support TLS-specific labels.</td></tr>
            <tr><td>Generated endpoint feature cohort<br/><code>datasets/ml/synthetic/synthetic_email_research_cohort_v1.csv</code></td><td>10,000 generated negotiation rows from 2,000 simulated endpoint profiles; SMTP 3,332, IMAP 3,336, POP3 3,332.</td><td>Current synthetic email posture classifier training and grouped evaluation.</td><td>Simulation; 0 real observations. One negotiated session's features predict a rubric on a generated full profile; not 10,000 PCAPs.</td></tr>
            <tr><td>Controlled email PCAP testbed<br/><code>testbed/captures/</code></td><td>110 synthetic captures, 116 parsed streams in the latest runtime audit.</td><td>Parser, Rule Engine, feature extraction, runtime routing, and controlled regression checks.</td><td>Generated traffic, never represented as real. Includes SMTP, IMAP, POP3, TLS states, routine combinations, and selected edge cases.</td></tr>
            <tr><td>Real TLS/HTTPS corpus<br/><code>datasets/ml/tls/mix.zip</code></td><td>41,205 TLS 1.3 HTTPS PCAP observations; approximately 3.6 GB; 41 site groups.</td><td>Separate general TLS behavior/novelty model.</td><td>Real HTTPS, not SMTP/IMAP/POP3. It is not used to claim email anomaly performance.</td></tr>
            <tr><td>MTA-STS and scan-context certificate records<br/><code>datasets/posture/mta-sts/</code></td><td>67,970 policy records reported in the project collection. An earlier source inventory estimated approximately 23,475 certificate-bearing results; the current versioned feature manifest records 21,490 successful parsed certificates and 9,459 unique fingerprints.</td><td>Certificate feature-diversity and novelty reference; policy context.</td><td>Source-level and processed counts differ across collection snapshots. Model evaluation uses the versioned 21,490-row parsed cohort. These are scan/HTTP-context certificates, not SMTP TLS handshakes.</td></tr>
            <tr><td>IMAP / POP3 ZGrab checks<br/><code>datasets/ml/zgrab/imap_Mexico.json</code><br/><code>datasets/ml/zgrab/pop3_Mexico.json</code></td><td>100 Mexico-derived targets per service on ports 143/110; 74 successful responses each. IMAPS port 993 had one banner-only success.</td><td>Real service/banner and capability context, including STARTTLS advertisement.</td><td>Not a broad cryptographic TLS training set: successful implicit-TLS probe did not yield negotiated TLS/certificate details.</td></tr>
            <tr><td>MAWI traces and EFF STARTTLS policy information<br/><code>datasets/newdataset/</code></td><td>Supplementary real network/policy evidence.</td><td>Context and feasibility exploration.</td><td>Examined MAWI daily traces use 96-byte snaplen and are not complete TLS-handshake evidence.</td></tr>
            <tr><td>Certificate Transparency / crt.sh<br/><code>datasets/posture/</code></td><td>Publicly retrievable certificate records and PEM data.</td><td>Certificate parser validation and certificate-feature diversity, where retained.</td><td>Transparency issuance records are separate from certificates observed in a particular email session.</td></tr>
            <tr><td>NVD, CISA KEV, EPSS<br/><code>datasets/threat-intelligence/</code></td><td>Vulnerability and exploitation-likelihood reference data.</td><td>Deterministic enrichment after an evidence-backed technology/CVE mapping.</td><td>Not classifier training data. No CVE is guessed from TLS version, cipher, or certificate attributes.</td></tr>
            <tr><td>CWE, NIST controls, OWASP references<br/><code>datasets/rag/</code></td><td>Security knowledge/reference material.</td><td>Supporting remediation and security context.</td><td>Knowledge sources, not observations, labels, or training examples for network models.</td></tr>
          </tbody></table></div>
          <div className="paper-callout"><b>Observed SMTP sample</b><span>Within the 1,600 active SMTP observations, TLS versions were TLS 1.2 in 528 sessions and TLS 1.0 in two. The remaining records do not become “secure” examples: many did not produce a completed TLS handshake. The TLS/certificate classifier cohort is therefore much narrower than 1,600.</span></div>
          <Figure number="4" title="Counts within the 1,600-record active SMTP scan cohort" caption="These are nested observation counts, not mutually exclusive classes. The 530 TLS handshakes and certificates form a subset of the total; STARTTLS availability is observed in 531 records. Non-TLS or failed observations are not treated as cryptographically secure negatives."><div className="charts-grid"><BarChart title="SMTP scan outcomes" max={1600} rows={[{ label: 'SMTP success', value: 1524, color: '#9b9695' }, { label: 'SMTP failure', value: 76, color: '#e82e3e' }]} note="Denominator: 1,600 targeted IPs. Active ZGrab2 observations."/><BarChart title="Encryption evidence observed" max={1600} rows={[{ label: 'STARTTLS observed', value: 531, color: '#e82e3e' }, { label: 'TLS handshake', value: 530, color: '#b9a8a9' }, { label: 'Certificate', value: 530, color: '#777275' }, { label: 'No TLS handshake record', value: 1070, color: '#343236' }]} note="Nested counts; absence of handshake evidence is not a negative security label."/></div></Figure>
        </Section>

        <Section id="testbed" index="06" title="Controlled testbed construction and scenario coverage">
          <p>The testbed was designed to provide known packet-level inputs for checking the parser and deterministic analysis, including protocol detection, STARTTLS transitions, negotiated TLS fields, and certificate outcomes. Its scenario matrix describes controlled combinations rather than a statistically representative population. The routine combinations were resolved against available runtime cipher support, while dedicated cases cover phenomena that are difficult to express with a stock service configuration.</p>
          <p>Ordinary Postfix, Dovecot, OpenSSL, and related components enforce minimum-security constraints or do not expose all desired protocol behaviors. Some weak or legacy cases therefore require isolated configurations or specialized MITM/fault-injection harnesses. This is a testability constraint, not evidence that the behaviors cannot occur. Conversely, a matrix row whose expected cipher strength contradicts the protocol/cipher universe must remain explicitly unresolvable instead of manufacturing a PCAP that falsely appears to satisfy the specification.</p>
          <Figure number="5" title="Scenario matrix resolution status (126 contracts)" caption="Resolution describes the execution contract audit, not 126 successful captures. The 110-capture runtime corpus is a separate artifact count. Several dedicated harness cases remain not implemented; 11 matrix expectations are internally contradictory and 6 cleartext cases correctly have no TLS negotiation."><div className="resolution-grid"><div className="resolution-number"><b>126</b><span>scenario contracts</span></div><BarChart title="Matrix resolution audit" max={126} rows={[{ label: 'Standard resolved', value: 90, color: '#9b9695' }, { label: 'Dedicated harness', value: 19, color: '#e82e3e' }, { label: 'Unresolvable oracle', value: 11, color: '#6f686a' }, { label: 'Not applicable: cleartext', value: 6, color: '#383539' }]} note="90 + 19 + 11 + 6 = 126 documented contracts."/><div className="resolution-note"><b>110 PCAP files</b><p>The current synthetic capture corpus is a runtime test set, not one capture per matrix contract. In the latest fresh audit, 110 captures produced 116 protocol streams with no analysis failures.</p><b>Dedicated harness != completed</b><p>The contract report lists 19 special cases; a subset is marked not implemented, including some IMAP STARTTLS stripping, HelloRetryRequest, selected TLS 1.3 resumption, extension, and early-data cases.</p></div></div></Figure>
          <p>For end-to-end testing, scenario drivers configure SMTP, IMAP, or POP3 clients against the isolated testbed services, capture traffic at the test network, and submit the resulting PCAP to the same offline parser used for user uploads. Expected observations and parser output can then be compared without training on the expected fixture labels. This creates a strong integration check for implementation correctness, but synthetic capture agreement cannot estimate real-world prevalence or false-positive rates.</p>
        </Section>

        <Section id="ml" index="07" title="Machine-learning models and task definitions">
          <p>ML is an auxiliary analysis layer, not an alternate policy engine. Current runtime routing selects a model based on protocol and available features, and returns a result, coverage, provenance, model identity, and availability/abstention state. Scores are uncalibrated unless explicitly stated otherwise; novelty scores are cohort-relative rather than probabilities.</p>
          <div className="model-cards">
            <ModelCard title="SMTP evidence-rubric risk classifier" badge="SUPERVISED · REAL ACTIVE SMTP DATA"><p><b>Question.</b> Which of three project-defined evidence-rubric categories best matches an evaluable SMTP scan record?</p><p><b>Target.</b> CRITICAL when SMTP has neither STARTTLS nor TLS, or an explicit NULL/RC4/EXPORT cipher; HIGH for enumerated legacy TLS, static RSA, SHA-1, weak/invalid/untrusted certificate conditions or no SAN; otherwise LOW_OR_MEDIUM. CBC/no-PFS alone is coarsened into LOW_OR_MEDIUM because there was only one medium-only example. Label totals are 994 CRITICAL, 62 HIGH, and 468 LOW_OR_MEDIUM.</p><p><b>Inputs.</b> 15 observed SMTP/TLS/certificate features, excluding IP, country, timestamps, identifiers, and rule flags. The model pipeline encodes categorical fields and tracks numeric missingness; it does not read Rule Engine verdicts.</p><p><b>Training/evaluation.</b> 1,524 evaluable rows from 1,600 active ZGrab records; 76 failures/incomplete cases are not evaluable. Country-disjoint train/validation/test = 849 / 292 / 383, with train classes 551/33/265, validation 154/13/125, and test 289/16/78 (CRITICAL/HIGH/LOW_OR_MEDIUM). Logistic Regression and Random Forest were searched on validation; a simplicity tie-break selected balanced Logistic Regression. Test macro-F1 0.944 versus majority baseline 0.287.</p><p><b>Interpretation.</b> It learns the stated rubric, not independent security truth and not the ability to catch conditions outside that rubric. Active scan to passive PCAP transfer is not validated.</p></ModelCard>
            <ModelCard title="Synthetic IMAP / POP3 posture classifier" badge="SUPERVISED · PROGRAMMATIC SIMULATION"><p><b>Question.</b> Can one observed negotiation vector estimate a four-tier rubric assigned to its generated endpoint profile?</p><p><b>Target.</b> LOW, MEDIUM, HIGH, CRITICAL based on the full simulated endpoint configuration: TLS availability, cipher support, key exchange, and certificate properties. The balanced generated cohort has 2,500 examples per class. Inputs describe an individual negotiation, so the target includes broader profile properties not necessarily visible in that one observation.</p><p><b>Inputs and split.</b> 15 canonical features; 10,000 generated rows from 2,000 simulated profiles, grouped by 508 configuration fingerprints. Train/validation/test = 6,390 / 1,735 / 1,875 rows with disjoint groups; the test supports are 570 LOW, 475 MEDIUM, 520 HIGH, and 310 CRITICAL.</p><p><b>Selection.</b> Logistic Regression validation macro-F1 0.490 vs Random Forest 0.473; Logistic Regression retained. Test macro-F1 0.511 versus majority baseline 0.071. Runtime routes this cohort to IMAP/POP3 only; it is not a real IMAP/POP3 training set.</p><p><b>Interpretation.</b> The result is within the designed simulator only. A runtime audit on the separate 110 PCAP corpus showed skewed IMAP/POP3 predictions and is execution coverage, not held-out accuracy.</p></ModelCard>
            <ModelCard title="SMTP rule-tier and rule-flag proxy models" badge="SUPERVISED · TARGET DERIVED FROM RULES"><p><b>Question.</b> Can a model reproduce defined Rule Engine-derived labels from a reduced observation vector?</p><p><b>Target.</b> One binary proxy predicts whether any of seven rule flags would fire; a second predicts LOW/MEDIUM/HIGH from those flags. These are intentionally named proxies, not independent risk classifiers.</p><p><b>Data.</b> 530 ZGrab SMTP TLS handshakes; the tier labels are 469 LOW, 41 MEDIUM, 20 HIGH. Country-disjoint train/validation/test is 298 / 138 / 94. For the tier proxy, test macro-F1 is 0.808 vs majority baseline 0.302; the binary compatibility proxy's grouped out-of-fold macro-F1 is 0.953 and confusion matrix is [[465,4],[6,55]]. Runtime coverage gating abstains below the training cohort's low-coverage boundary.</p><p><b>Interpretation.</b> Their measured agreement is rule-label reproduction. They cannot demonstrate that ML discovers issues missed by the rules and should not be presented as the principal risk model.</p></ModelCard>
            <ModelCard title="SMTP configuration novelty" badge="UNSUPERVISED / SUPPORT · SMTP COHORT"><p><b>Question.</b> Is the observed negotiated tuple unusual relative to the ZGrab SMTP TLS reference?</p><p><b>Features and reference.</b> TLS version, cipher suite, and key-exchange tuple; the named reference contains 469 SMTP TLS observations. The runtime exact-tuple support signal is primary; a learned Isolation Forest score is secondary because controlled transfer checks showed missed weak/broken combinations.</p><p><b>Output.</b> Anomaly score/flag, reference cohort, feature coverage, and whether the exact tuple was seen. The result indicates rarity relative to this active scan sample, not insecurity. A common insecure tuple may be within-reference; a secure rare tuple may be unusual.</p><p><b>Validation boundary.</b> No independent labeled real SMTP anomaly set exists. Injected unseen tuples test lookup behavior only.</p></ModelCard>
            <ModelCard title="Certificate novelty" badge="UNSUPERVISED · CERTIFICATE COHORT"><p><b>Question.</b> Does a certificate feature vector differ from a scan-context reference distribution?</p><p><b>Features.</b> 22 parsed fields covering key/signature properties, validity, SANs, self-signing, CA and server-auth use, key usages, extension counts, chain information, OCSP/CRL/SCT/policy indicators, and observation state.</p><p><b>Reference and output.</b> Fit/reference grouping uses 7,567 unique fingerprints from the 21,490 parsed observations. A held-out set contains 1,892 unique fingerprints; 77 were flagged under the configured review-tail setting. Runtime can score only when a leaf certificate is observable.</p><p><b>Interpretation.</b> No vulnerability labels exist. Novelty means uncommon in this corpus, not invalid or malicious. Source certificates came from SMTP-related scan/HTTP context rather than complete SMTP handshakes.</p></ModelCard>
            <ModelCard title="HTTPS/TLS novelty model" badge="UNSUPERVISED · SEPARATE NON-EMAIL COHORT"><p><b>Purpose.</b> Explore cohort-relative TLS behavior on 41,205 real HTTPS PCAPs; the captured observations are TLS 1.3 and grouped by 41 site identifiers.</p><p><b>Method.</b> Isolation Forest with a reference fit on 32,160 observations across 32 site groups and a held-out 9,045 observations from nine site groups. The configured 1% contamination setting flags 52 in the held-out reference evaluation.</p><p><b>Boundary.</b> This model does not run as an SMTP/IMAP/POP3 detector and cannot support claims about insecure TLS, legacy TLS, or email-specific anomaly detection. No independent anomaly labels are present.</p></ModelCard>
          </div>
          <Figure number="6" title="Which model can run for which observation?" caption="Runtime applicability is driven by protocol and observable feature coverage. A missing feature leads to not-evaluable/abstention where required; there is no silent transfer between data cohorts."><div className="data-table-wrap"><table className="data-table routing-table"><thead><tr><th>Incoming stream / evidence</th><th>Model output path</th><th>Training/reference provenance</th><th>Expected interpretation</th></tr></thead><tbody><tr><td>SMTP with enough SMTP/TLS facts</td><td>Evidence-rubric classifier; SMTP tuple novelty; certificate novelty if leaf observable</td><td>Active ZGrab SMTP; separate SMTP scan-context certificate corpus</td><td>Advisory rubric category; tuple rarity; certificate novelty</td></tr><tr><td>IMAP or POP3 negotiation</td><td>Synthetic email posture classifier; certificate novelty only if certificate visible</td><td>Generated endpoint profile cohort; separate certificate corpus</td><td>Experimental simulated-cohort estimate; not real-world validation</td></tr><tr><td>SMTP / IMAP / POP3 with no TLS</td><td>Protocol/state rules; classifiers may abstain for insufficient required features</td><td>Observed capture evidence</td><td>Not applicable or not evaluable is preserved; no “safe” default</td></tr><tr><td>General HTTPS capture</td><td>HTTPS novelty model is separate, not routed into mail analysis</td><td>41,205 real HTTPS/TLS PCAP cohort</td><td>General TLS cohort novelty only</td></tr></tbody></table></div></Figure>
        </Section>

        <Section id="evaluation" index="08" title="Evaluation protocol and measured results">
          <p>Evaluation separates implementation verification from predictive effectiveness. Supervised model selection uses a validation partition; the final metric is calculated on a held-out test partition. Related rows are grouped to reduce record-level leakage: ZGrab splits are by country; simulated email rows are grouped by generated endpoint-configuration fingerprint; certificate data is grouped by certificate fingerprint; and HTTPS observations are grouped by site. These groupings reduce specific leakage paths but do not establish independence from broader service, operator, or collection-process effects.</p>
          <div className="result-cards"><div><span>REAL SMTP RUBRIC</span><b>0.944</b><small>macro-F1 · test n=383</small><p>Country-disjoint test. Agreement with a project rubric, not security ground truth.</p></div><div><span>SYNTHETIC MAIL POSTURE</span><b>0.511</b><small>macro-F1 · test n=1,875</small><p>Configuration-group-disjoint test, but wholly within a designed simulator.</p></div><div><span>RULE-TIER PROXY</span><b>0.808</b><small>macro-F1 · test n=94</small><p>Predicts labels derived from rule flags; not an independent risk target.</p></div></div>
          <p>Accuracy is included only as a secondary quantity. Class imbalance and asymmetric consequences make macro-averaged metrics and per-class support more informative. Table 2 gives test-set precision, recall, F1, and support. The test results are not directly comparable across rows because the targets, protocols, collection methods, and label sources differ.</p>
          <div className="data-table-wrap"><table className="data-table research-table"><caption>Table 2. Held-out supervised classification metrics</caption><thead><tr><th>Model / target</th><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>Support</th></tr></thead><tbody>
            <tr><td rowSpan={3}>ZGrab evidence rubric<br/>macro-F1 0.944 · accuracy 0.990</td><td>LOW_OR_MEDIUM</td><td>0.951</td><td>1.000</td><td>0.975</td><td>78</td></tr><tr><td>HIGH</td><td>1.000</td><td>0.750</td><td>0.857</td><td>16</td></tr><tr><td>CRITICAL</td><td>1.000</td><td>1.000</td><td>1.000</td><td>289</td></tr>
            <tr><td rowSpan={4}>Synthetic endpoint posture<br/>macro-F1 0.511 · accuracy 0.513</td><td>LOW</td><td>0.806</td><td>0.351</td><td>0.489</td><td>570</td></tr><tr><td>MEDIUM</td><td>0.500</td><td>0.507</td><td>0.504</td><td>475</td></tr><tr><td>HIGH</td><td>0.676</td><td>0.629</td><td>0.651</td><td>520</td></tr><tr><td>CRITICAL</td><td>0.293</td><td>0.626</td><td>0.400</td><td>310</td></tr>
            <tr><td rowSpan={3}>Rule-tier proxy<br/>macro-F1 0.808 · accuracy 0.936</td><td>LOW</td><td>0.962</td><td>0.974</td><td>0.968</td><td>78</td></tr><tr><td>MEDIUM</td><td>0.600</td><td>0.600</td><td>0.600</td><td>5</td></tr><tr><td>HIGH</td><td>0.900</td><td>0.818</td><td>0.857</td><td>11</td></tr>
          </tbody></table></div>
          <div className="matrix-grid"><Matrix title="ZGrab evidence rubric · test n=383" labels={['LOW / MED', 'HIGH', 'CRITICAL']} rows={[[78, 0, 0], [4, 12, 0], [0, 0, 289]]}/><Matrix title="Synthetic posture · test n=1,875" labels={['LOW', 'MED', 'HIGH', 'CRITICAL']} rows={[[200, 61, 7, 302], [48, 241, 74, 112], [0, 140, 327, 53], [0, 40, 76, 194]]}/><Matrix title="Rule-tier proxy · test n=94" labels={['LOW', 'MED', 'HIGH']} rows={[[76, 2, 0], [1, 3, 1], [2, 0, 9]]}/></div>
          <p className="metric-footnote">Matrix rows are actual classes and columns are predictions. The 4/16 held-out HIGH ZGrab examples confused as LOW_OR_MEDIUM; the synthetic model has substantial LOW/CRITICAL confusion. These patterns are important limits, not cosmetic details. Per-class metrics and target definitions must accompany any headline score.</p>
          <h3 className="subhead">8.1 Anomaly and novelty evaluation</h3>
          <p>Unsupervised models have no independent real anomaly labels, so they do not have conventional anomaly accuracy, precision, or recall. Project validation uses held-out cohort groups to inspect score distributions and controlled feature-injection checks to verify that the runtime responds to specified novel values. Injection metrics answer “did this implementation flag our deliberately altered test vector?” They do not answer “does it detect real attacks?”</p>
          <div className="data-table-wrap"><table className="data-table research-table"><caption>Table 3. Novelty-model checks and what they establish</caption><thead><tr><th>Model</th><th>Reference / held-out real controls</th><th>Controlled mock test</th><th>Permitted conclusion</th></tr></thead><tbody>
            <tr><td>SMTP exact-tuple support</td><td>469 SMTP observations; 7 distinct reference tuples</td><td>2 seen and 2 constructed unseen tuples; perfect separation by exact membership</td><td>Lookup/inference path works. The test is tautological and too small to be detector accuracy.</td></tr>
            <tr><td>Certificate Isolation Forest</td><td>7,567 reference fingerprints; 1,892 unique held-out certificates</td><td>379 controls + 379 injected variants; macro-F1 0.979, ROC-AUC 0.995; 4.2% control flags under this recipe</td><td>Responds to those artificial perturbations. Not certificate vulnerability classification or operational false-positive rate.</td></tr>
            <tr><td>HTTPS Isolation Forest</td><td>32,160 fit observations / 32 site groups; 9,045 holdout / 9 site groups</td><td>3,015 controls + 3,015 injected variants; macro-F1 0.921, ROC-AUC 1.000</td><td>Responds to large injected changes on a few held-out sites; not an email or attack detector.</td></tr>
            <tr><td>SMTP tuple transfer audit</td><td>59 evaluable synthetic SMTP scenarios compared with real scan cohort</td><td>8/8 BROKEN, 6/6 WEAK, 7/7 MEDIUM and 12/38 HIGH-strength tuples unseen; secondary Isolation Forest missed all 8 BROKEN and 6 WEAK tuples</td><td>Describes behavior on named controlled cases only. Strength categories are not independent anomaly labels.</td></tr>
          </tbody></table></div>
          <p>For the HTTPS model, the configured 1% contamination parameter is a review-tail choice, not an empirically measured false-positive rate. For certificate novelty, the 5% review-tail threshold similarly selects observations for review; it does not define vulnerability. For the SMTP support model, exact tuple rarity is directly defined by cohort membership. The stronger Isolation Forest behavior cannot be assumed simply because the model class is unsupervised.</p>
        </Section>

        <Section id="runtime" index="09" title="Runtime integration, outputs, and threat prioritization">
          <p>For every uploaded capture, the analysis service parses streams, evaluates deterministic rules, computes posture separately, and invokes the ML runtime when enabled. ML routing is protocol-specific: SMTP uses the active-ZGrab evidence-rubric model; IMAP and POP3 use the synthetic endpoint-posture model; SMTP-specific anomaly/rarity is not applied to IMAP/POP3. Certificate novelty runs only when the capture yields enough leaf-certificate features. Required-input coverage can lead to abstention or a not-evaluable result. There is no fallback that silently applies an HTTPS or synthetic model to the wrong mail cohort.</p>
          <p>Each ML output is structured with a model identity/version, prediction or flag, score/confidence where applicable, observed-feature coverage, source cohort/provenance, and status. Class scores and confidence are explicitly uncalibrated. Novelty results include the reference cohort and do not claim probability of compromise. During the latest fresh synthetic runtime audit, the parser handled 110 captures as 116 streams: SMTP 68, IMAP 24, POP3 24, with no analysis failures. The audit establishes parser/runtime execution and applicability. It is not a predictive test set for the models.</p>
          <h3 className="subhead">Threat prioritization and recommendations</h3>
          <p>The threat-intelligence path is enrichment rather than classifier training. A finding can be linked to a CVE only when captured evidence supports a defensible product/version or vulnerability relationship. If an evidenced CVE is present, local NVD records, CISA KEV membership, and EPSS can add severity, known-exploitation, and exploit-likelihood context. TLS 1.0, CBC, or an expired certificate does not by itself identify a CVE. When no grounded mapping exists, the finding remains a cryptographic policy finding without fabricated vulnerability attribution.</p>
          <p>Mitigation guidance is generated from the finding class and attached evidence, for example removing deprecated protocol support or renewing a certificate whose validity evidence failed. It is deterministic and evidence-linked; it should not be described as an ML-generated remediation plan. Reports provide a case summary, stream records, protocol and TLS details, certificate evidence, policy results, posture method, anomaly/model outputs, source limitations, and available recommendations. JSON and HTML exports are available, with print-to-PDF from the report view.</p>
          <Figure number="7" title="Interpretation ladder for a single captured stream" caption="The order prevents category errors: the analyst sees raw evidence and deterministic checks before interpreting advisory model outputs and external context. Unavailable evidence is stated rather than treated as a pass."><div className="interpretation-ladder"><div><span>1</span><b>Observed connection</b><small>SMTP / IMAP / POP3 · TLS · certificate fields</small></div><div><span>2</span><b>Forensic state</b><small>STARTTLS transition · handshake · visibility</small></div><div><span>3</span><b>Deterministic result</b><small>named check · pass/fail/not observable · evidence</small></div><div><span>4</span><b>Separate ML advisory</b><small>rubric prediction or cohort-relative novelty</small></div><div><span>5</span><b>Evidence-linked context</b><small>recommendation · CVE/KEV/EPSS only if mapped</small></div></div></Figure>
        </Section>

        <Section id="limitations" index="10" title="Limitations, validity, and responsible interpretation">
          <div className="limitations-grid"><div><b>1 · Label validity</b><p>The real SMTP classifier predicts a hand-authored evidence rubric. Rule-proxy labels derive from existing deterministic outputs. The synthetic classifier learns generated profile rubrics. No model is trained on independent human-reviewed security-risk labels.</p></div><div><b>2 · Population validity</b><p>ZGrab is active scanning of 16 country target lists and samples one observation per target, not representative passive enterprise traffic. Model transfer to uploaded PCAPs is unvalidated. IMAP/POP3 service scans are too limited for real crypto training.</p></div><div><b>3 · Synthetic model behavior</b><p>The routed IMAP/POP3 classifier's grouped test macro-F1 is 0.511 and critical-class precision is 0.293. This warrants cautious experimental display; it is not production-grade effectiveness.</p></div><div><b>4 · Anomaly labels</b><p>There are no independent real anomaly labels. Injection benchmarks are tests of response to constructed changes. “Unusual” is not equivalent to vulnerable, malicious, or suspicious.</p></div><div><b>5 · Passive visibility</b><p>Packet loss, one-sided captures, truncation, encrypted TLS 1.3 handshake messages, absent SNI, and unknown external trust-store state can limit conclusions. “Not observed” does not mean “does not exist.”</p></div><div><b>6 · Certificate corpus shift</b><p>Certificate novelty uses scan/HTTP-context records, not a population of complete SMTP TLS handshakes. Certificate aging, duplicate handling, and source-population drift can alter novelty scores.</p></div><div><b>7 · Policy and posture</b><p>Guideline checks depend on profile, mode, and available facts. The 0–100 posture score is a deterministic heuristic, not an ML risk score or calibrated compliance rating.</p></div><div><b>8 · Threat attribution</b><p>NVD/KEV/EPSS improve prioritization only after a defensible vulnerability link. Weak cryptography alone does not establish a CVE or exploitation.</p></div></div>
          <p className="paper-callout-text">Accordingly, the strongest validated claims concern parsing behavior on the controlled testbed, deterministic processing of observed evidence, artifact loading and runtime routing, and held-out prediction of the explicitly documented labels. The project does not yet demonstrate production-grade risk accuracy, independent anomaly detection effectiveness, or an ML system that reliably discovers weaknesses missed by the Rule Engine.</p>
        </Section>

        <Section id="reproducibility" index="11" title="Reproducibility and implementation records">
          <p>Model artifacts are persisted with metadata and checked against registered schema and SHA-256 digests at load time. Training and evaluation manifests record feature definitions, label rules, grouped splits, class distributions, model-selection process, metrics, and source hashes. The local dataset manifests include SHA-256 digests for each of the 16 raw country scan files; for example, the HTTPS archive digest is recorded in <code>datasets/ml/metadata/https_tls_v1.json</code>, and the scan-certificate archive digest is in <code>datasets/ml/metadata/mta_sts_certificates_v1.json</code>. Large capture archives are not embedded in the browser report; source project and upstream provider links are listed in References. Where a local archive's original public release URL is not pinned in metadata, the project path and digest identify the exact artifact more reliably than an inferred external download link.</p>
          <div className="repro-grid"><div><span>Parser / session schema</span><code>analysis/parser.py<br/>analysis/starttls.py<br/>analysis/tls_session.py<br/>analysis/cert_validator.py</code></div><div><span>Policy / posture</span><code>analysis/rule_engine/<br/>analysis/posture.py</code></div><div><span>ML runtime / artifacts</span><code>analysis/ml_runtime.py<br/>models/*.json<br/>models/metadata/</code></div><div><span>Label and feature contract</span><code>datasets/ml/FEATURE_LABEL_CONTRACT.md</code></div><div><span>Evaluation and runtime audit</span><code>datasets/ml/ML_VALIDATION_REPORT.md<br/>models/synthetic_pcap_runtime_coverage_v5.json</code></div><div><span>Testbed contract and matrix</span><code>data/scenario_contracts.json<br/>data/matrix_resolution_report.md<br/>testbed/captures/</code></div></div>
          <p>The repository includes tests for model loading/inference, missing-data handling, protocol applicability, parser-to-runtime execution on the synthetic PCAP suite, and controlled novelty injections. Passing these tests establishes implementation behavior for their fixtures. It does not establish calibrated risk or generalization to previously unseen production networks.</p>
        </Section>

        <Section id="references" index="12" title="References and dataset access">
          <p>The references below include normative protocol/security guidance and upstream data/tool sources. Project-local paths identify the exact collected or generated artifacts. Several datasets are large or subject to source-provider access conditions and are therefore linked to their upstream source rather than served as direct report downloads.</p>
          <ol className="references research-references">
            <li>Klensin, J. <a href="https://www.rfc-editor.org/rfc/rfc3207" target="_blank" rel="noreferrer">RFC 3207: SMTP Service Extension for Secure SMTP over Transport Layer Security</a>. IETF, 2002. STARTTLS protocol behavior.</li>
            <li>Resnick, P. <a href="https://www.rfc-editor.org/rfc/rfc2595" target="_blank" rel="noreferrer">RFC 2595: Using TLS with IMAP, POP3 and ACAP</a>. IETF, 1999.</li>
            <li>Rescorla, E. <a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noreferrer">RFC 8446: The Transport Layer Security (TLS) Protocol Version 1.3</a>. IETF, 2018.</li>
            <li>Cooper, D. et al. <a href="https://csrc.nist.gov/pubs/sp/800/52/r2/final" target="_blank" rel="noreferrer">NIST SP 800-52 Rev. 2: Guidelines for the Selection, Configuration, and Use of TLS Implementations</a>. NIST, 2019.</li>
            <li>Barker, E. <a href="https://csrc.nist.gov/pubs/sp/800/131/a/r2/final" target="_blank" rel="noreferrer">NIST SP 800-131A Rev. 2: Transitioning the Use of Cryptographic Algorithms and Key Lengths</a>. NIST, 2019.</li>
            <li>Mozilla. <a href="https://wiki.mozilla.org/Security/Server_Side_TLS" target="_blank" rel="noreferrer">Server Side TLS Guidelines, version 6.0</a>. Guideline profiles used by the Rule Engine; version and rule pack should be checked against the repository's vendored data.</li>
            <li>Rescorla, E. <a href="https://www.rfc-editor.org/rfc/rfc5280" target="_blank" rel="noreferrer">RFC 5280: Internet X.509 Public Key Infrastructure Certificate and CRL Profile</a>. IETF, 2008.</li>
            <li>Saint-Andre, P. &amp; Google. <a href="https://www.rfc-editor.org/rfc/rfc8461" target="_blank" rel="noreferrer">RFC 8461: SMTP MTA Strict Transport Security (MTA-STS)</a>. IETF, 2018.</li>
            <li>University of Michigan / ZMap Project. <a href="https://github.com/zmap/zgrab2" target="_blank" rel="noreferrer">ZGrab2 source and documentation</a>. Modular application-layer scanner used for active protocol measurement.</li>
            <li>Censys. <a href="https://docs.censys.com/" target="_blank" rel="noreferrer">Censys platform documentation</a>. Source of target discovery context; this project collected its own bounded target lists.</li>
            <li>MAWI Working Group. <a href="https://mawi.wide.ad.jp/mawi/" target="_blank" rel="noreferrer">MAWI Working Group Traffic Archive</a>. Supplementary real network traces; examined short-snaplen traces cannot supply complete handshake evidence.</li>
            <li>crt.sh. <a href="https://crt.sh/" target="_blank" rel="noreferrer">Certificate Search</a>. Certificate Transparency lookup service used in certificate collection/exploration.</li>
            <li>FIRST. <a href="https://www.first.org/epss/" target="_blank" rel="noreferrer">Exploit Prediction Scoring System (EPSS)</a>. External prioritization context, not a model training label here.</li>
            <li>CISA. <a href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog" target="_blank" rel="noreferrer">Known Exploited Vulnerabilities Catalog</a>. Evidence-linked known-exploitation enrichment.</li>
            <li>NIST. <a href="https://nvd.nist.gov/developers" target="_blank" rel="noreferrer">National Vulnerability Database API documentation</a>. CVE records used only after supported mapping.</li>
            <li>SecureMailScope project repository: <a href="https://github.com/Ben160804/SES-v1" target="_blank" rel="noreferrer">github.com/Ben160804/SES-v1</a>. The repository contains the implementation, testbed, dataset manifests, and local data paths described in this report.</li>
            <li>Project artifacts: <code>datasets/ml/zgrab/</code> · <code>datasets/ml/tls/mix.zip</code> · <code>datasets/ml/synthetic/</code> · <code>datasets/posture/mta-sts/</code> · <code>datasets/threat-intelligence/</code> · <code>datasets/rag/</code> · <code>testbed/captures/</code>.</li>
            <li>Project methods and validation: <code>datasets/ml/ML_VALIDATION_REPORT.md</code> · <code>datasets/ml/FEATURE_LABEL_CONTRACT.md</code> · <code>data/matrix_resolution_report.md</code> · <code>data/scenario_contracts.json</code>.</li>
          </ol>
          <p className="paper-endnote">Dataset sizes and reported metrics are tied to local project snapshots as of 30 September 2026. Upstream datasets evolve; exact reproducibility requires the corresponding local source files, model artifact digests, feature contract, and split manifests.</p>
        </Section>
        <footer className="paper-footer"><Brand compact /><span>SIH 26159 · TECHNICAL RESEARCH REPORT · 2026</span></footer>
      </article>
    </div>
  </div>
}
