"""
testbed/runner/test_data_integrity.py
====================================
Data Integrity and Architectural Separation Tests (SecureMailScope Testbed).

Proves that:
  1. build_observed_artifact takes ONLY (scenario_id, analyzer_results) — zero spec access.
  2. Zero spec leakage into observed artifact (no raw CSV fields, no fallback values).
  3. All streams are preserved in observed.json without stream-0 flattening.
  4. TLS 1.3 (PCAP-005) leaves unobservable encrypted cert as null in observed,
     while expected preserves intent, and comparator reports INCONCLUSIVE.
  5. All 126 scenarios in matrix produce expected.json validating against expected_schema.json.
  6. Observed artifact strictly validates against observed_schema.json.
  7. Comparison artifact strictly validates against comparison_schema.json.
  8. ScenarioExecutionResult does NOT have sidecar_path or sidecar_data, and DOES have
     expected_path, observed_path, comparison_path, comparison_status, execution_success.
  9. Assertions structure generated by to_expected_dict contains required booleans and
     observability modes (always, conditional, not_applicable).
"""

import inspect
import json
from pathlib import Path
import unittest
import jsonschema

from testbed.runner.spec import ScenarioSpec, load_matrix
from testbed.runner.observed import build_observed_artifact, serialize_evidence
from testbed.runner.comparator import compare
from testbed.runner.runner import ScenarioExecutionResult

_project_root = Path(__file__).resolve().parent.parent.parent


class TestDataIntegrity(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.matrix = {s.scenario_id: s for s in load_matrix()}
        with open(_project_root / "data" / "expected_schema.json", "r", encoding="utf-8") as f:
            cls.expected_schema = json.load(f)
        with open(_project_root / "data" / "observed_schema.json", "r", encoding="utf-8") as f:
            cls.observed_schema = json.load(f)
        with open(_project_root / "data" / "comparison_schema.json", "r", encoding="utf-8") as f:
            cls.comparison_schema = json.load(f)

    def test_01_observed_signature_zero_spec_access(self):
        """Prove build_observed_artifact takes only (scenario_id, analyzer_results)."""
        sig = inspect.signature(build_observed_artifact)
        param_names = list(sig.parameters.keys())
        self.assertEqual(
            param_names,
            ["scenario_id", "analyzer_results"],
            f"build_observed_artifact signature must only be (scenario_id, analyzer_results), got: {param_names}"
        )

    def test_02_no_spec_leakage_into_observed(self):
        """Observed output contains only wire telemetry, zero spec / matrix columns."""
        dummy_results = {
            0: {
                "protocol": "SMTP",
                "starttls": {"status": "UPGRADED"},
                "tls": {"tls_version": "TLS 1.3"},
                "certificate": None,
            }
        }
        obs = build_observed_artifact("PCAP-005", dummy_results)
        obs_json = json.dumps(obs)

        forbidden_keys = [
            "spec", "matrix", "oracle", "raw_row", "manifest",
            "cert_sig_algo", "cipher_strength", "auth_outcome",
            "server_sends_fatal_alert", "strip_starttls"
        ]
        for key in forbidden_keys:
            self.assertNotIn(f'"{key}"', obs_json, f"Forbidden key '{key}' leaked into observed artifact!")

    def test_03_all_streams_preserved_in_observed(self):
        """Observed artifact preserves all analyzed streams without discarding any."""
        multi_stream_results = {
            0: {"protocol": "SYN_SCAN"},
            1: {"protocol": "SMTP", "tls": {"tls_version": "TLS 1.2"}},
            2: {"protocol": "POP3", "tls": {"tls_version": "TLS 1.3"}},
        }
        obs = build_observed_artifact("PCAP-001", multi_stream_results)
        jsonschema.validate(instance=obs, schema=self.observed_schema)

        self.assertIn("0", obs["sessions"])
        self.assertIn("1", obs["sessions"])
        self.assertIn("2", obs["sessions"])
        self.assertEqual(len(obs["sessions"]), 3)

    def test_04_pcap005_tls13_unobservable_cert_handling(self):
        """Prove TLS 1.3 unobservable certificate produces INCONCLUSIVE, null in observed, intent in expected."""
        spec = self.matrix["PCAP-005"]
        expected = spec.to_expected_dict()
        jsonschema.validate(instance=expected, schema=self.expected_schema)

        self.assertEqual(expected["expected"]["cert_sig_algo"], "ECDSA")
        self.assertEqual(expected["assertions"]["certificate.signature_algorithm"]["observability"], "conditional")

        # Passive analyzer observes TLS 1.3 handshake with encrypted cert -> cert is null
        observed_results = {
            0: {
                "protocol": "SMTP",
                "starttls": {"status": "UPGRADED"},
                "tls": {
                    "tls_version": "TLS 1.3",
                    "cipher_strength": "strong",
                    "cipher_name": "TLS_AES_256_GCM_SHA384",
                    "forward_secrecy": True,
                },
                "certificate": None,
            }
        }
        observed = build_observed_artifact("PCAP-005", observed_results)
        jsonschema.validate(instance=observed, schema=self.observed_schema)

        # Wire certificate is null
        self.assertIsNone(observed["sessions"]["0"]["certificate"])

        # Compare
        comp = compare(expected, observed)
        jsonschema.validate(instance=comp, schema=self.comparison_schema)

        self.assertEqual(comp["status"], "INCONCLUSIVE")
        self.assertEqual(len(comp["mismatches"]), 0)
        self.assertIn("certificate.signature_algorithm", comp["unknowns"])
        self.assertEqual(comp["fields"]["certificate.signature_algorithm"]["status"], "UNOBSERVABLE")

    def test_05_all_126_scenarios_validate_against_expected_schema(self):
        """All 126 scenario matrix rows project to valid expected.json artifacts."""
        self.assertEqual(len(self.matrix), 126, "Expected exactly 126 matrix scenarios")
        for sc_id, spec in self.matrix.items():
            exp = spec.to_expected_dict()
            try:
                jsonschema.validate(instance=exp, schema=self.expected_schema)
            except jsonschema.ValidationError as err:
                self.fail(f"Scenario {sc_id} expected_dict failed validation: {err.message}")

    def test_06_observed_schema_strictness(self):
        """Observed schema rejects extraneous top-level properties (additionalProperties: false)."""
        bad_obs = {
            "schema_version": "1.0",
            "scenario_id": "PCAP-001",
            "sessions": {},
            "extra_leaked_spec_field": "oops"
        }
        with self.assertRaises(jsonschema.ValidationError):
            jsonschema.validate(instance=bad_obs, schema=self.observed_schema)

    def test_07_comparison_schema_strictness(self):
        """Comparison schema rejects invalid status and extra properties."""
        bad_comp = {
            "schema_version": "1.0",
            "scenario_id": "PCAP-001",
            "status": "MAYBE",  # Invalid enum
            "fields": {},
            "mismatches": [],
            "unknowns": [],
            "evaluated_stream": 0,
        }
        with self.assertRaises(jsonschema.ValidationError):
            jsonschema.validate(instance=bad_comp, schema=self.comparison_schema)

    def test_08_scenario_execution_result_dataclass_audit(self):
        """Prove ScenarioExecutionResult has no sidecar fields and has the correct new fields."""
        fields = [f.name for f in ScenarioExecutionResult.__dataclass_fields__.values()]

        # Must NOT have sidecar fields
        self.assertNotIn("sidecar_path", fields, "sidecar_path must be removed from ScenarioExecutionResult")
        self.assertNotIn("sidecar_data", fields, "sidecar_data must be removed from ScenarioExecutionResult")

        # Must have the 3-layer paths and status fields
        expected_fields = [
            "expected_path",
            "observed_path",
            "comparison_path",
            "expected_data",
            "observed_data",
            "comparison_data",
            "comparison_status",
            "execution_success",
            "success",
        ]
        for ef in expected_fields:
            self.assertIn(ef, fields, f"Missing required field '{ef}' on ScenarioExecutionResult")

    def test_09_to_expected_dict_assertions_structure(self):
        """Verify assertions map contains required flags and valid observability modes."""
        spec = self.matrix["PCAP-001"]
        exp = spec.to_expected_dict()
        assertions = exp["assertions"]

        valid_modes = {"always", "conditional", "not_applicable"}
        for key, assertion in assertions.items():
            self.assertIn("required", assertion, f"Assertion '{key}' missing 'required' flag")
            self.assertIsInstance(assertion["required"], bool, f"Assertion '{key}' 'required' must be bool")
            self.assertIn("observability", assertion, f"Assertion '{key}' missing 'observability' mode")
            self.assertIn(assertion["observability"], valid_modes, f"Assertion '{key}' has invalid mode: {assertion['observability']}")


if __name__ == "__main__":
    unittest.main()
