import os
import warnings
from cryptography import x509
from cryptography.utils import CryptographyDeprecationWarning
from cryptography.x509.verification import Store

# Filter non-compliant root CA serial number warning from legacy bundle certs per RFC 5280
warnings.filterwarnings("ignore", category=CryptographyDeprecationWarning)


class TrustStoreManager:
    """
    TRUST STORE DESIGN (Swappable at Construction Time):
    -----------------------------------------------------------------------
    WHY 'testbed' IS THE DEFAULT:
      All PCAPs in this project are synthetic lab captures signed by our own
      generated root CA (data/test_root_ca.pem). Using 'production' (Mozilla
      bundle) would classify every test cert as UNTRUSTED_SELF_SIGNED, which
      is misleading during development. The default is 'testbed' so running
      the parser against lab captures gives accurate trust signals.
      For real production mail server captures, pass trust_store='production'.

    WHY WE STORE _store_certs AS A SEPARATE LIST:
      cryptography.x509.verification.Store is an opaque object — you cannot
      iterate or introspect its contents after construction. For the self-signed
      case (Case 1 in extract_certificate()), we need to check whether the cert
      is a member of the active trust store by object equality. We therefore
      keep _store_certs as the raw list of x509.Certificate objects alongside
      the Store so we can do:
          any(leaf_obj == root for root in self._store_certs)

    TRUST STORE MODES:
      - 'production': Mozilla CA root bundle (certifi.where()). Use for
        analyzing real-world email traffic from external mail servers.
      - 'testbed':    Local lab root CA (data/test_root_ca.pem). Use for
        analyzing synthetic captures generated by our own test CA.
      - custom:       A pre-built cryptography.x509.verification.Store object.
        Allows callers to supply their own enterprise or national trust bundle.
    """
    def __init__(self, trust_store="testbed", base_dir=None):
        # -------------------------------------------------------------------
        # TRUST STORE ARGUMENT VALIDATION:
        # -------------------------------------------------------------------
        # WHY STRICT VALIDATION IS MANDATORY (FAIL-FAST CONFIGURATION):
        #   TrustStoreManager explicitly supports two named presets ('testbed',
        #   'production') and custom pre-built cryptography.x509.verification.Store
        #   instances. Previously, arbitrary inputs (such as typos like 'producton')
        #   fell through into the custom Store handler, causing delayed, obscure
        #   crashes down the line. We enforce strict validation immediately at
        #   construction time to fail fast on misconfigurations.
        if trust_store not in ("testbed", "production") and not isinstance(trust_store, Store):
            raise ValueError(
                f"Invalid trust_store argument: {trust_store!r}. "
                "Must be 'testbed', 'production', or a cryptography.x509.verification.Store instance."
            )

        self.trust_store_type = trust_store
        self.base_dir = base_dir or os.path.dirname(os.path.abspath(__file__))
        self._loaded_store = None
        self._store_certs = []
        self.trust_store_description = ""

    def get_store(self):
        """
        LAZY TRUST STORE LOADER:
        -----------------------------------------------------------------------
        WHY LAZY-LOAD AND NOT LOAD IN __init__:
          Loading the Mozilla CA bundle (300+ certs) or parsing PEM files is
          non-trivial I/O. Methods like detect_protocol() and detect_starttls()
          never touch the trust store. Lazy-loading avoids paying this cost for
          callers who never invoke extract_certificate().

        WHY load_pem_x509_certificates (plural):
          Both the certifi bundle and our testbed PEM may contain multiple
          concatenated PEM blocks. x509.load_pem_x509_certificates() iterates
          all of them and returns a list, which we then pass to Store().
        """
        if self._loaded_store is not None:
            return self._loaded_store

        self._store_certs = []

        if self.trust_store_type == "production":
            # certifi.where() returns the path to Mozilla's curated CA bundle.
            # This is the same bundle used by Python's ssl module and pip.
            # Appropriate for validating real external mail server certificates.
            import certifi
            with open(certifi.where(), "rb") as f:
                self._store_certs = x509.load_pem_x509_certificates(f.read())
            self._loaded_store = Store(self._store_certs)
            self.trust_store_description = (
                f"production (Mozilla CA bundle via certifi, {len(self._store_certs)} roots)"
            )

        elif self.trust_store_type == "testbed":
            # Our own generated root CA, created specifically for these lab PCAPs.
            # Path is relative to this script's directory to make it portable
            # regardless of the working directory the script is called from.
            ca_path = os.path.join(self.base_dir, "..", "data", "test_root_ca.pem")
            if os.path.exists(ca_path):
                with open(ca_path, "rb") as f:
                    self._store_certs = x509.load_pem_x509_certificates(f.read())
                self._loaded_store = Store(self._store_certs)
                self.trust_store_description = (
                    f"testbed ({os.path.abspath(ca_path)}, {len(self._store_certs)} root(s))"
                )
            else:
                # Degrade gracefully: empty store means nothing will be trusted,
                # but the parser won't crash. The description surfaces the warning.
                self._loaded_store = Store([])
                self._store_certs = []
                self.trust_store_description = (
                    f"testbed (WARNING: {ca_path} not found, empty store)"
                )

        elif isinstance(self.trust_store_type, Store):
            # Caller passed a pre-built Store object directly (custom enterprise bundle).
            # We cannot introspect it for _store_certs, so Case 1 self-signed check
            # (object-equality membership test) will always return False for custom stores.
            self._loaded_store = self.trust_store_type
            self.trust_store_description = "custom user-provided Store"

        else:
            raise ValueError(
                f"Invalid trust_store argument: {self.trust_store_type!r}. "
                "Must be 'testbed', 'production', or a cryptography.x509.verification.Store instance."
            )

        return self._loaded_store

    def get_ca_file_path(self):
        """
        Resolves the on-disk CA bundle file path for external tools (e.g. openssl verify).
        """
        if self.trust_store_type == "testbed":
            ca_path = os.path.join(self.base_dir, "..", "data", "test_root_ca.pem")
            if os.path.exists(ca_path):
                return ca_path
            return None
        elif self.trust_store_type == "production":
            import certifi
            return certifi.where()
        return None
