import os
import warnings
from cryptography import x509
from cryptography.utils import CryptographyDeprecationWarning
from cryptography.x509.verification import Store

# Filter non-compliant root CA serial number warning from legacy bundle certs per RFC 5280
warnings.filterwarnings("ignore", category=CryptographyDeprecationWarning)


class TrustStoreManager:
    """
    TRUST STORE DESIGN (Swappable at Construction Time):
    -----------------------------------------------------------------------
    WHY 'testbed' IS THE DEFAULT:
      All PCAPs in this project are synthetic lab captures signed by our own
      generated root CA (data/test_root_ca.pem). Using 'production' (Mozilla
      bundle) would classify every test cert as UNTRUSTED_SELF_SIGNED, which
      is misleading during development. The default is 'testbed' so running
      the parser against lab captures gives accurate trust signals.
      For real production mail server captures, pass trust_store='production'.

    WHY WE STORE _store_certs AS A SEPARATE LIST:
      cryptography.x509.verification.Store is an opaque object — you cannot
      iterate or introspect its contents after construction. For the self-signed
      case (Case 1 in extract_certificate()), we need to check whether the cert
      is a member of the active trust store by object equality. We therefore
      keep _store_certs as the raw list of x509.Certificate objects alongside
      the Store so we can do:
          any(leaf_obj == root for root in self._store_certs)

    TRUST STORE MODES:
      - 'production': Mozilla CA root bundle (certifi.where()). Use for
        analyzing real-world email traffic from external mail servers.
      - 'testbed':    Local lab root CA (data/test_root_ca.pem). Use for
        analyzing synthetic captures generated by our own test CA.
      - custom:       A pre-built cryptography.x509.verification.Store object.
        Allows callers to supply their own enterprise or national trust bundle.
    """
    def __init__(self, trust_store="testbed", ca_path=None, base_dir=None):
        # -------------------------------------------------------------------
        # TRUST STORE ARGUMENT VALIDATION & CA PATH RESOLUTION:
        # -------------------------------------------------------------------
        # Priority order:
        #   1. Explicit ca_path (file path to PEM bundle or scenario-specific trust store).
        #   2. Named presets:
        #      - 'production': Mozilla CA root bundle via certifi.where().
        #      - 'testbed':    Persistent testbed root CA (testbed/pki/ca/root_ca.crt)
        #                      with fallback to legacy data/test_root_ca.pem if present.
        #   3. Pre-built cryptography.x509.verification.Store instance.
        self.base_dir = base_dir or os.path.dirname(os.path.abspath(__file__))
        self._loaded_store = None
        self._store_certs = []
        self.trust_store_description = ""
        self.ca_file_path = None

        if ca_path is not None:
            self.ca_file_path = os.path.abspath(str(ca_path))
            self.trust_store_type = "custom_path"
        elif isinstance(trust_store, Store):
            self.trust_store_type = trust_store
        elif trust_store in ("testbed", "production"):
            self.trust_store_type = trust_store
            if trust_store == "production":
                import certifi
                self.ca_file_path = certifi.where()
            elif trust_store == "testbed":
                # Primary testbed PKI root generated by testbed/pki/generator/make_certs.py
                testbed_root = os.path.join(self.base_dir, "..", "testbed", "pki", "ca", "root_ca.crt")
                legacy_root = os.path.join(self.base_dir, "..", "data", "test_root_ca.pem")
                if os.path.exists(testbed_root):
                    self.ca_file_path = os.path.abspath(testbed_root)
                elif os.path.exists(legacy_root):
                    self.ca_file_path = os.path.abspath(legacy_root)
                else:
                    self.ca_file_path = os.path.abspath(testbed_root)
        elif isinstance(trust_store, (str, os.PathLike)) and os.path.isfile(str(trust_store)):
            self.ca_file_path = os.path.abspath(str(trust_store))
            self.trust_store_type = "testbed"
        else:
            raise ValueError(
                f"Invalid trust_store argument: {trust_store!r}. "
                "Must be 'testbed', 'production', a valid CA/trust store file path, an explicit ca_path, or a cryptography.x509.verification.Store instance."
            )

    def get_store(self):
        """
        LAZY TRUST STORE LOADER:
        -----------------------------------------------------------------------
        WHY LAZY-LOAD AND NOT LOAD IN __init__:
          Loading the Mozilla CA bundle (300+ certs) or parsing PEM files is
          non-trivial I/O. Methods like detect_protocol() and detect_starttls()
          never touch the trust store. Lazy-loading avoids paying this cost for
          callers who never invoke extract_certificate().

        WHY load_pem_x509_certificates (plural):
          Both the certifi bundle and our testbed PEM may contain multiple
          concatenated PEM blocks. x509.load_pem_x509_certificates() iterates
          all of them and returns a list, which we then pass to Store().

        EMPTY PEM HANDLING:
          For self_signed_untrusted scenarios (and empty trust stores), an empty
          file is handled cleanly by creating an empty Store([]) without error.
        """
        if self._loaded_store is not None:
            return self._loaded_store

        self._store_certs = []

        if isinstance(self.trust_store_type, Store):
            # Caller passed a pre-built Store object directly (custom enterprise bundle).
            self._loaded_store = self.trust_store_type
            self.trust_store_description = "custom user-provided Store"
            return self._loaded_store

        if self.ca_file_path and os.path.exists(self.ca_file_path):
            with open(self.ca_file_path, "rb") as f:
                content = f.read()

            # ponytail: handle empty PEM (0-byte file or whitespace only).
            # Used by self_signed_untrusted scenarios (empty trust store).
            if not content.strip():
                self._store_certs = []
                self._loaded_store = None
                self.trust_store_description = f"empty trust store ({self.ca_file_path}, 0 roots)"
            else:
                try:
                    self._store_certs = x509.load_pem_x509_certificates(content)
                except Exception:
                    self._store_certs = []

                if self._store_certs:
                    self._loaded_store = Store(self._store_certs)
                else:
                    self._loaded_store = None
                type_name = self.trust_store_type if isinstance(self.trust_store_type, str) else "custom"
                self.trust_store_description = (
                    f"{type_name} ({self.ca_file_path}, {len(self._store_certs)} root(s))"
                )
        else:
            # Degrade gracefully: empty store means nothing will be trusted,
            # but the parser won't crash. The description surfaces the warning.
            self._loaded_store = None
            self._store_certs = []
            type_name = self.trust_store_type if isinstance(self.trust_store_type, str) else "custom"
            self.trust_store_description = (
                f"{type_name} (WARNING: {self.ca_file_path} not found, empty store)"
            )

        return self._loaded_store

    def get_ca_file_path(self):
        """
        Resolves the on-disk CA bundle file path for external tools (e.g. openssl verify).
        Returns the absolute path if existing, or None.
        """
        if self.ca_file_path and os.path.exists(self.ca_file_path):
            return self.ca_file_path
        return None
